<Project Sdk="Aspire.AppHost.Sdk/13.6.0">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" Version="13.6.0" />
    <PackageReference Include="Aspire.Hosting.Redis" Version="13.6.0" />
    <PackageReference Include="Aspire.Hosting.MongoDB" Version="13.6.0" />
    <PackageReference Include="Aspire.Hosting.Kafka" Version="13.6.0" />
    <PackageReference Include="Aspire.Hosting.JavaScript" Version="13.6.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Reservation.Api\Reservation.Api.csproj" />
    <ProjectReference Include="..\MicroBooker.StorageWorker\MicroBooker.StorageWorker.csproj" />
  </ItemGroup>

</Project>
